language: android

addons:
  apt:
    packages:
      - lynx
android:
  components:
  - build-tools-27.0.2
  - android-27
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-27

  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

script:
- ./gradlew clean test build
after_failure:
- if [ -f home/travis/build/jawnpaul/Med-Manager/app/build/reports/lint-results.html ]; then lynx -dump home/john/Desktop/lint-results.html; fi
